# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 529d3ccef0017ed290beb98a72c28b6c02b0b3a390a6dc8c170378c012ccdcada6ca6768e357121f6345fc10654487656ff48c30fb4a87584a3a2431cd4e3461

test:
  secret_key_base: 0153c58edebc7c3639952bcb39fcc6aaa7536b8e070388af8a7672d05bf551e987d60135af29398aac076cbccd1a65a6563df1c5a0ad8b9ac4344e076e9cf7e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
